# Hexo Configuration
title: FreedomGPT
url: https://freedomgpt.top
root: /
permalink: :year/:month/:day/:title/
tag_dir: tags
archive_dir: archives
category_dir: categories

# 核心：使用 next 主题
theme: next

# 核心：直接搬运静态 sitemap
skip_render:
  - "sitemap.xml"

# 分类映射
category_map:
  "vps技巧": vps

highlight:
  enable: true
  line_number: true
