# Hexo Configuration
title: FreedomGPT
url: https://www.freedomgpt.top
root: /
permalink: :year/:month/:day/:title/
tag_dir: tags
archive_dir: archives
category_dir: categories

# 核心：使用 next 主题
theme: next

# 核心：映射分类名，解决重复问题
category_map:
  "vps技巧": vps

# 核心：直接搬运 sitemap，不进行渲染
skip_render:
  - "sitemap.xml"

# 基础显示配置
index_generator:
  path: ''
  per_page: 10
  order_by: -date

highlight:
  enable: true
  line_number: true
